{{- if and .Values.gateway.enabled .Values.gateway.podDisruptionBudget.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "arhiax.gateway.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "arhiax.gateway.labels" . | nindent 4 }}
spec:
  {{- if .Values.gateway.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.gateway.podDisruptionBudget.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.gateway.podDisruptionBudget.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "arhiax.gateway.selectorLabels" . | nindent 6 }}
{{- end }}
